## 9.2.1 抛出异常
如果需要在程序中自行抛出异常，则应使用 throw 语句。 throw 语句可以单独使用， throw
语句抛出的不是异常类，而是一个异常实例，而且每次只能抛出一个异常实例

```text
throw ExceptionInstance
```

由于 Kotlin 没有 checked 异常（即使某个异常在 Java 中原本是 checked 异常，在 Kotlin
中它也不是 checked 异常），因此 Kotlin 抛出异常的语句无须放在 try 块中，程序既可以显式使
用 try...catch 来捕获井处理该异常，也可以完全不理会该异常，把该异常交给该方法调用者处
理
```kotlin

fun main(args: Array<String>) {
    // 不是该异常在Java中是否为checked异常。
    // 在Kotlin中该异常都不是checked异常
    throwChecked(-3)
    throwRuntime(3)
}
fun throwChecked(a: Int) {
    if (a > 0) {
        // 自行抛出普通异常，在Kotlin中也不是checked异常
        // 该代码不必处于try块里，也不必处于带throws声明的方法中
        throw Exception("a的值大于0，不符合要求")
    }
}
fun throwRuntime(a: Int) {
    if (a > 0) {
        throw RuntimeException("a的值大于0，不符合要求")
    }
}
```
## 9.2.2 自定义异常类

用户自定义异常都应该继承 Exception 基类，定义异常类时通常需要提供两个构造器： 一
个是无参数的构造器；另一个是带一个字符串参数的构造器，这个字符串将作为该异常对象的
描述信息（也就是异常对象的 message 属性的返回值） 

```kotlin
class AuctionException: Exception{
	// 无参数的构造器
	constructor() {}       // ①
	// 带一个字符串参数的构造器
	constructor(msg: String): super(msg) {}  // ②
}
```

## 9.2.3 catch 和 throw 同时使用
```kotlin

public class AuctionTest{
    var initPrice: Double = 30.0
    fun bid(bidPrice: String){
        var d: Double
        try {
            d = bidPrice.toDouble()
        } catch (e: Exception) {
            // 此处完成本方法中可以对异常执行的修复处理
            // 此处仅仅是在控制台打印异常的跟踪栈信息
            e.printStackTrace()
            // 再次抛出自定义异常
            throw AuctionException("竞拍价必须是数值，"
                    + "不能包含其他字符！")
        }
        if (initPrice > d){
            throw AuctionException("竞拍价比起拍价低，"
                    + "不允许竞拍！")
        }
        initPrice = d
    }
}
fun main(args: Array<String>) {
    val at = AuctionTest()
    try{
        at.bid("df")
    }catch (ae: AuctionException){
        // 再次捕获到bid()方法中的异常，并对该异常进行处理
        println(ae.message)
    }
}
```

## 9.2.4 异常链
捕获一个异常，然后抛出另 一个异常，并把原始异常信息保存下来，这是一种典型的链式
处理（ 23 种设计模式之一：职责链模式），也被称为“异常链”。

## 9.2.5 throw 语句是表达式

与 try i吾句是表达式一样， Kotlin 的 throw 语句也是表达式，但由于 throw 表达式的类型
比较特殊，是 Nothing 类型，因此很少将 throw 语句赋值给其他变量，但我们可以在 Elvis 表
达式中使用 throw 表达式 

```kotlin
class User(var name: String? = null, var pass: String? = null)
fun main(args: Array<String>) {
    val user = User()
    // 在Elvis表达式中使用throw表达式
    // throw表达式表示程序出现异常，不会真正对变量赋值
    val th: String = user.name ?: throw NullPointerException("目标对象不能为null")
    println(th)

    val s: String = user.name ?: fail("目标对象不能为null")
    println(s)
}
fun fail(message: String): Nothing {
    throw IllegalArgumentException(message)
}
```

>Nothing 类型没有值，而是用于标记永远无法“真正”返回的表达式，因此程序不会获取
 表达式的值 。 当我们 自己定义函数时 ，也可使用 Nothing 来标记一个永远不会返回的函数
